configuration: Debug 

environment:
  app_version: '2.0.1'

version: '%app_version%.{build}'

assembly_info:
  patch: true
  file: SolutionInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"	
  assembly_informational_version: "%app_version%"

cache:
  packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

before_build:
  nuget restore

nuget:
  account_feed: true

build:
  publish_nuget: true
  verbosity: minimal

test:
  assemblies:
    - OSPSuite.BDDHelper.Tests.dll

skip_branch_with_pr: true

branches:
  only:
  - master
  - develop

skip_commits:
  files:
    - '*.md'

pull_requests: 
  do_not_increment_build_number: true     

nuget: 
  disable_publish_on_pr: true  

notifications:
  - provider: Slack
    incoming_webhook:      
      secure: 4MH9Em6TtrKalq6808dhPOqypTfYBJvVlqPaa9akNyF1h7st5qNdNezFp6T+bWXqrcZ4q/smtPcJ7LkUFHL46JDYUFlIL8FDz+ApX/vP+x0=    